### ISSUE TITLE
error update

### ISSUE THREAD

**Issue by m1faridi** [du-song/AppProxyCap#8]
AppProxyCap % git submodule update
Cloning into '/Users/mac/Desktop/untitled folder 10/shadowsocks-iOS/AppProxyCap/lib/inject_and_interpose'...
fatal: unable to connect to github.com:
github.com[0: 140.82.121.4]: errno=Operation timed out

**Comment by du-song** [comment]
@m1faridi the git link should be working as you can see on GitHub web. 

Please retry in case it's your network errors, otherwise you can clone that repo manually.
